travis:
  secure:
    BINSTAR_TOKEN: tXVbxELVHMcbhMqJS0g/E9IXO4xdhdu0q1TTahyu93i4A5PgyZjUvd9S0e8wMctZj0su8qsRPvyJHgyQTX8xz9GqrmpkZ7BtZT5vqTtvpee2OpekD0cXGiPg1CaOhO/z1U/qppaQDjZQD8l3D8gl4uMydaM9JX+jTnMOdscKJZPaHonVj/cuGRhpEqUZa+J+gJ3VWENkyj2zjXWPWGhlkbL4Lpk36lhVtEAgNiRqoyCNwU6dzIHqfkU39hC7A7/qMa4M5US76hr6w/1k1s/2YmN9xmsfPjdJlgNh1a+8K3NFKAES2TKNuwyWSHtQpHlEXHUMEudvUWyQreGNrgMOUPbW2fFOdNt54R2nrXfE5mAlb6kcKXc1fUUYQ3L/Ps9nROwXkt2OLCkmZQpKd3T9o27Dqck8iNKKLS76HxVuTM03C1+y+OrGWGzZdAoKpl190PqU4IcY9/V7s+3rae/YNtOGJvntICblYsKKTitVHh1WoRwgq0kHWPhEcSg+fIcJOhJ7zAmeBDyh6JARAe+9HezZq7KUzAjonQT5yGrCXI5lxH5dVWvWWDIic7DLzaKGhWZKvba3yw1V6u8qgxWDXU7jPOL2irEoXf/kk4zYpz6oRvgmwZfjqvfoZ4hqqnBBhV+k4iK/WsyKQea/PwShOjJdTALVsanFWjbfcMml6AQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
